version: "3.8"

volumes:
  dbsql:


services:
  db:
    container_name: app-db
    image: mysql:8
    restart: always
    volumes:
      - dbsql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=password
    expose:
      - 3306
  app:
    container_name: message-app
    restart: always
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
      - redis
      - elasticsearch
  redis:
    container_name: app-redis
    image: redis:alpine
    restart: always
    expose:
      - 6379
  elasticsearch:
    # image: elasticsearch:7.17.18
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    restart: always
    container_name: elasticsearch
    volumes:
      - dbsql:/var/lib/elasticsearch
    expose:
      - 9200
